--Category's
insert into category ( name )values ('Electronic');
insert into  category ( name) values ('Home');
insert into category ( name ) values ('Grocery');

--Products
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Ergo','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Art','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','New Style','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Comfort','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Exclusive','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Art','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Ergo','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Perseus','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Art','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Tempo','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Relax','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Perseus','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Art','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Ergo','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','New Style','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Magnifisense','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','New Style','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Boreal','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Tempo','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Perseus','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Magnifisense','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Art','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Magnifisense','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Ergo','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Art','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Ergo','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Art','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Perseus','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Comfort','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','New Style','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Tempo','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Magnifisense','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Perseus','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Perseus','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Magnifisense','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Exclusive','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Magnifisense','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Perseus','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Relax','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Magnifisense','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Art','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Tempo','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Perseus','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Comfort','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Tempo','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Ergo','Plazas : 2', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','New Style','Plazas : 3', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Rosen','Comfort','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Suavestar','Perseus','Plazas : 1', 0);
insert into product(id_category,brand,name, unity, quantity) values (2,'Cannon','Magnifisense','Plazas : 3', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 320','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 320','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 320','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 320','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 321','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 321','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 321','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 321','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 322','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 322','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 322','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 322','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 323','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 323','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 323','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 323','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 324','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 324','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 324','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 324','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 325','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 325','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 325','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 325','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 326','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 326','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 326','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 326','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 327','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 327','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 327','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 327','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 328','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 328','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 328','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 328','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 329','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 329','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 329','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 329','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 3210','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 3210','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 3210','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 3210','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 3211','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 3211','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 3211','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 3211','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 3212','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 3212','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 3212','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 3212','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 3213','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 3213','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 3213','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 3213','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','IdeaPad - 3214','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Lenovo','ThinkPad - 3214','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Ispiron - 3214','One', 0);
insert into product (id_category,brand,name,  unity, quantity) values (1,'Dell','Latitud - 3214','One', 0);
insert into product(id_category,brand,name, unity) values (3,'Coca-cola','Orange','250 ml');insert into product(id_category,brand,name, unity,quantity) values (3,'Gallo','0000','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Orange','750 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Spaghetti','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Lima Lemon','750 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','peanut','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Lima Lemon','500 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Ravioli','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','cola','1 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Lima Lemon','2 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Lima Lemon','1 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','cola','250 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Spaghetti','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Spaghetti','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Okita','000','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Okita','000','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','Nachos','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Sorrentino','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','Chips','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Gallo','0000','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','cola','1 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'BlancaFlor','0000','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Sorrentino','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Spaghetti','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','cola','250 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Okita','000','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','Chips','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','Chips','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','Nachos','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Ravioli','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Spaghetti','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Dos Hermanos','0000','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Gallo','000','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Gallo','000','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Dos Hermanos','0000','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','Chips','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Dos Hermanos','0000','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Gallo','0000','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Spaghetti','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Sorrentino','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','Nachos','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Orange','250 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','Nachos','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Orange','1 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Okita','000','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Sorrentino','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Sorrentino','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Orange','750 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Orange','500 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','Chips','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Spaghetti','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','cola','500 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Ravioli','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Spaghetti','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Gallo','0000','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Lima Lemon','250 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Orange','2 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Morixe','0000','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','cola','750 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','peanut','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Spaghetti','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','peanut','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Ravioli','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','peanut','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','cola','500 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','cola','2 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Dos Hermanos','0000','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Ravioli','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Orange','250 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Spaghetti','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Okita','0000','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Ravioli','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','Chips','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Sorrentino','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Sorrentino','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Lima Lemon','250 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'BlancaFlor','0000','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Sorrentino','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Sorrentino','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Spaghetti','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','Nachos','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','Chips','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Sorrentino','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Dos Hermanos','000','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Spaghetti','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Orange','2 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lucchetti','Ravioli','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Dos Hermanos','000','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','peanut','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Okita','0000','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Okita','0000','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Sorrentino','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Ravioli','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','peanut','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Orange','1 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','cola','2 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','Nachos','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','peanut','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','Chips','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Okita','0000','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'BlancaFlor','0000','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','Chips','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Morixe','0000','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','cola','750 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Dos Hermanos','000','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Ravioli','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Ravioli','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Gallo','000','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Lima Lemon','1 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Dos Hermanos','000','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Morixe','0000','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Lima Lemon','500 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','Nachos','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Ravioli','500 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Gallo','000','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Matarazo','Ravioli','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Pehuamar','peanut','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Lima Lemon','2 lt', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Coca-cola','Lima Lemon','750 ml', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','Nachos','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Krachitos','peanut','250 gr', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Molto','Sorrentino','150 gr' , 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Lays','Nachos','1 kl', 0);
insert into product(id_category,brand,name, unity,quantity) values (3,'Manaos','Orange','500 ml', 0);


--MovementType
insert into movementType (name) values ('Alta');
insert into movementType (name) values ('Baja');

--Movements
